# Generated by Django 5.0.6 on 2026-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('fleet_owner', 'Fleet Owner'), ('stage_manager', 'Stage Manager'), ('driver', 'Driver'), ('conductor', 'Conductor'), ('commuter', 'Commuter')], default='commuter', max_length=20),
        ),
    ]
