# Generated by Django 5.0.6 on 2026-07-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('routing', '0003_seat'),
        ('stage_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_route',
            field=models.ForeignKey(blank=True, help_text='Default route assigned to this driver/conductor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers', to='routing.route'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_stage',
            field=models.ForeignKey(blank=True, help_text='Default stage assigned to this driver', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers', to='stage_queue.stage'),
        ),
    ]
