# Generated by Django 5.0.6 on 2026-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_assigned_route_user_assigned_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_route',
        ),
        migrations.RemoveField(
            model_name='user',
            name='assigned_stage',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('fleet_owner', 'Fleet Owner'), ('driver', 'Driver'), ('conductor', 'Conductor'), ('commuter', 'Commuter')], default='commuter', max_length=20),
        ),
    ]
