# Generated by Django 5.0.6 on 2026-06-17 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_alter_route_tenant_alter_trip_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='routing.trip')),
            ],
            options={
                'ordering': ['trip', 'seat_number'],
                'unique_together': {('trip', 'seat_number')},
            },
        ),
    ]
