# Generated by Django 5.0.6 on 2026-07-08 12:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_seat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='route',
            name='max_pickup_distance_km',
            field=models.PositiveIntegerField(default=50, help_text='Maximum distance in km a bus can be from commuter and still be shown.'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='route',
            name='path',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(blank=True, help_text='For on-demand routes this is when the service started, not a fixed schedule.', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
