# Generated by Django 5.0.6 on 2026-07-09 09:40

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_alter_trip_options_route_max_pickup_distance_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('buffer_minutes', models.PositiveIntegerField(default=5, help_text='Minimum buffer time in minutes required for a safe transfer')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_as_first', to='routing.route')),
                ('first_route_stop', models.ForeignKey(help_text='Stop on first route where passenger alights to transfer', on_delete=django.db.models.deletion.CASCADE, related_name='linked_as_first_stop', to='routing.stop')),
                ('second_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_as_second', to='routing.route')),
                ('second_route_stop', models.ForeignKey(help_text='Stop on second route where passenger boards after transfer', on_delete=django.db.models.deletion.CASCADE, related_name='linked_as_second_stop', to='routing.stop')),
                ('transfer_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_routes', to='routing.transferstation')),
            ],
            options={
                'unique_together': {('first_route', 'second_route', 'transfer_station')},
            },
        ),
    ]
