# Generated by Django 5.0.6 on 2026-07-09 11:43

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0007_linkedbooking_missedconnectionevent_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PassTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier_type', models.CharField(choices=[('weekly', 'Weekly Bundle'), ('monthly', 'Monthly Season Pass'), ('postpaid', 'Post-Paid Line')], max_length=20)),
                ('trip_allowance', models.PositiveIntegerField(help_text='Number of trips included in the pass')),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Discount percentage off regular fare', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for the pass (if prepaid)', max_digits=10)),
                ('duration_days', models.PositiveIntegerField(help_text='Validity period in days')),
                ('min_credit_score', models.IntegerField(blank=True, help_text='Minimum credit score required for this tier', null=True)),
                ('max_credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum credit limit for post-paid tier', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-discount_percent'],
            },
        ),
        migrations.CreateModel(
            name='CommuterPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trips_remaining', models.PositiveIntegerField(default=0)),
                ('trips_used', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current outstanding balance for post-paid', max_digits=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Credit limit for post-paid tier', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commuter_passes', to='tenants.tenant')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'commuter'}, on_delete=django.db.models.deletion.CASCADE, related_name='commuter_passes', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passes', to='passes.passtier')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'tenant', 'status')},
            },
        ),
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=50, help_text='Credit score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_trips', models.PositiveIntegerField(default=0)),
                ('on_time_payments', models.PositiveIntegerField(default=0)),
                ('missed_payments', models.PositiveIntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'commuter'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Score',
                'verbose_name_plural': 'Credit Scores',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('charge', 'Charge'), ('payment', 'Payment'), ('adjustment', 'Adjustment'), ('settlement', 'Weekly Settlement')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pass_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='passes.commuterpass')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_applied', models.DecimalField(decimal_places=2, max_digits=8)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('route_name', models.CharField(blank=True, max_length=255)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_usage', to='booking.booking')),
                ('pass_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='passes.commuterpass')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklySettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=100)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pass_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_settlements', to='passes.commuterpass')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('pass_instance', 'week_start')},
            },
        ),
    ]
