# Generated by Django 5.0.6 on 2026-07-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passtier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pass_tiers', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='commuterpass',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='creditscore',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
