# Generated by Django 5.0.6 on 2026-07-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20260710_1328'),
        ('passes', '0002_passtier_tenant_alter_commuterpass_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passusage',
            name='trip_leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pass_usage', to='booking.tripleg'),
        ),
    ]
