# Generated by Django 5.0.6 on 2026-07-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passes', '0003_passusage_trip_leg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passusage',
            name='trip_leg',
        ),
    ]
