export const PAYMENT_METHODS = [
  {
    id: 'mpesa',
    name: 'M-Pesa',
    provider: 'Safaricom',
    color: '#00A651',
    type: 'mobile',
    description: 'Pay via STK push on your phone',
  },
  {
    id: 'airtel',
    name: 'Airtel Money',
    provider: 'Airtel Kenya',
    color: '#ED1C24',
    type: 'mobile',
    description: 'Pay from your Airtel line',
  },
  {
    id: 'kcb',
    name: 'KCB M-Pesa',
    provider: 'KCB Bank',
    color: '#005EB8',
    type: 'bank',
    description: 'Pay via KCB mobile banking',
  },
  {
    id: 'equity',
    name: 'Equitel / EazzyPay',
    provider: 'Equity Bank',
    color: '#E31837',
    type: 'bank',
    description: 'Pay via Equity mobile app',
  },
  {
    id: 'coop',
    name: 'MCo-op Cash',
    provider: 'Co-operative Bank',
    color: '#006838',
    type: 'bank',
    description: 'Pay via Co-op Bank USSD or app',
  },
  {
    id: 'ncba',
    name: 'NCBA Loop',
    provider: 'NCBA Bank',
    color: '#003366',
    type: 'bank',
    description: 'Pay via Loop mobile banking',
  },
]
