# Generated by Django 5.0.6 on 2026-07-10 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20260710_1328'),
        ('payments', '0002_alter_payment_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.bookingsession'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking'),
        ),
    ]
