# Generated by Django 5.0.6 on 2026-07-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_booking_session_alter_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking_session',
        ),
    ]
