# Generated by Django 5.0.6 on 2026-06-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_fleet_tenant_alter_vehicle_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='inspection_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
