# Generated by Django 5.0.6 on 2026-07-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehicle_inspection_expiry_vehicle_insurance_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fleet_code',
            field=models.CharField(blank=True, help_text='Short human-readable code printed on windshield, e.g. TH-047', max_length=20, null=True, unique=True),
        ),
    ]
