# Generated by Django 5.0.6 on 2026-07-07 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_vehicle_fleet_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assigned_conductor',
            field=models.ForeignKey(blank=True, help_text='Default conductor assigned to this vehicle', limit_choices_to={'role': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Default driver assigned to this vehicle', limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
