# Generated by Django 5.0.6 on 2026-07-08 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_vehicle_assigned_conductor_vehicle_assigned_driver'),
        ('routing', '0003_seat'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='assigned_route',
            field=models.ForeignKey(blank=True, help_text='Route assigned to this vehicle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='routing.route'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Default driver assigned to this vehicle (one driver per vehicle)', limit_choices_to={'role': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('assigned_driver__isnull', False)), fields=('assigned_driver',), name='unique_driver_assignment'),
        ),
    ]
