# Generated by Django 5.0.6 on 2026-07-08 11:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_vehicle_assigned_route_alter_vehicle_assigned_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Current GPS location of the vehicle', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_passengers',
            field=models.PositiveIntegerField(default=0, help_text='Current number of passengers on board'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='eta_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time of arrival in minutes for next stop', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_location_update',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last location update', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('parked', 'Parked'), ('en_route', 'En Route'), ('at_stage', 'At Stage'), ('loading', 'Loading'), ('full', 'Full - Ready to Depart')], default='parked', help_text='Current operational status of the vehicle', max_length=20),
        ),
    ]
