# Generated by Django 5.0.6 on 2026-07-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_vehicle_current_location_vehicle_current_passengers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='current_passengers',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='eta_minutes',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_location_update',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
    ]
