# Generated by Django 5.0.6 on 2026-06-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_hold_expires_at'),
        ('routing', '0003_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='alighting_stop',
            field=models.ForeignKey(blank=True, help_text='Where the commuter gets off. Null = rides to route end.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alightings', to='routing.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='boarding_stop',
            field=models.ForeignKey(blank=True, help_text='Where the commuter gets on. Null = boards at route origin.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boardings', to='routing.stop'),
        ),
    ]
