# Generated by Django 5.0.6 on 2026-06-18 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_alighting_stop_booking_boarding_stop'),
        ('routing', '0003_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='boarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='short_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='alighting_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alightings', to='routing.stop'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='boarding_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boardings', to='routing.stop'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('boarded', 'Boarded')], default='held', max_length=20),
        ),
    ]
