# Generated by Django 5.0.6 on 2026-06-18 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_boarded_at_booking_short_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='commuter',
            field=models.ForeignKey(blank=True, help_text='Null for cash walk-up bookings recorded by a conductor.', limit_choices_to={'role': 'commuter'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
