# Generated by Django 5.0.6 on 2026-07-09 09:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_commuter'),
        ('routing', '0005_transferstation_linkedroute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('transfer_complete', 'Transfer Complete'), ('missed_connection', 'Missed Connection'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_leg_booking', models.ForeignKey(help_text='Booking for the first route (Bus 1)', on_delete=django.db.models.deletion.CASCADE, related_name='linked_as_first_leg', to='booking.booking')),
                ('linked_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_bookings', to='routing.linkedroute')),
                ('second_leg_booking', models.ForeignKey(help_text='Booking for the second route (Bus 2)', on_delete=django.db.models.deletion.CASCADE, related_name='linked_as_second_leg', to='booking.booking')),
                ('transfer_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_bookings', to='routing.transferstation')),
            ],
            options={
                'unique_together': {('first_leg_booking', 'second_leg_booking')},
            },
        ),
        migrations.CreateModel(
            name='MissedConnectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_leg_eta_minutes', models.FloatField(help_text='ETA of Bus 1 to transfer station when event was triggered')),
                ('second_leg_departure_buffer', models.FloatField(help_text='Time difference between Bus 1 ETA and Bus 2 departure')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_leg_trip', models.ForeignKey(help_text='Bus 1 that was delayed', on_delete=django.db.models.deletion.CASCADE, related_name='missed_connections_as_first', to='routing.trip')),
                ('linked_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_connection_events', to='booking.linkedbooking')),
                ('second_leg_trip', models.ForeignKey(help_text='Bus 2 that was missed', on_delete=django.db.models.deletion.CASCADE, related_name='missed_connections_as_second', to='routing.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionalVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Voucher expiration date (typically 30 days from issue)')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('missed_connection_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='booking.missedconnectionevent')),
                ('original_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_vouchers', to='booking.booking')),
                ('redeemed_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_vouchers', to='booking.booking')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'commuter'}, on_delete=django.db.models.deletion.CASCADE, related_name='transactional_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
