# Generated by Django 5.0.6 on 2026-07-09 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_linkedbooking_missedconnectionevent_and_more'),
        ('routing', '0005_transferstation_linkedroute'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('preferred_departure_time', models.TimeField(help_text='Preferred departure time for this day')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alighting_stop', models.ForeignKey(blank=True, help_text='Preferred alighting stop for this day (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_schedules_alighting', to='routing.stop')),
                ('boarding_stop', models.ForeignKey(blank=True, help_text='Preferred boarding stop for this day (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_schedules_boarding', to='routing.stop')),
                ('commuter', models.ForeignKey(limit_choices_to={'role': 'commuter'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, help_text='Preferred route for this day (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='routing.route')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['commuter', 'day_of_week'],
                'unique_together': {('commuter', 'tenant', 'day_of_week')},
            },
        ),
    ]
