# Generated by Django 5.0.6 on 2026-07-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_weeklyschedule'),
        ('routing', '0005_transferstation_linkedroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_two_way',
            field=models.BooleanField(default=False, help_text='Whether this is a two-way (round trip) booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_alighting_stop',
            field=models.ForeignKey(blank=True, help_text='Alighting stop for return journey', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_alightings', to='routing.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_pickup_stop',
            field=models.ForeignKey(blank=True, help_text='Pickup stop for return journey', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_pickups', to='routing.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_trip',
            field=models.ForeignKey(blank=True, help_text='Return trip for two-way bookings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bookings', to='routing.trip'),
        ),
        migrations.DeleteModel(
            name='WeeklySchedule',
        ),
    ]
