# Generated by Django 5.0.6 on 2026-07-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_weeklyschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_two_way',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_alighting_stop',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_pickup_stop',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_trip',
        ),
        migrations.DeleteModel(
            name='WeeklySchedule',
        ),
    ]
