# Generated by Django 5.0.6 on 2026-07-10 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_booking_is_two_way_and_more'),
        ('routing', '0005_transferstation_linkedroute'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_two_way',
            field=models.BooleanField(default=False, help_text='Whether this is part of a two-way (round trip) booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='leg_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Order of this leg in two-way booking (1=outbound, 2=return)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('boarded', 'Boarded'), ('missed_delay', 'Missed Due to Delay'), ('re_routed', 'Re-Routed'), ('refunded', 'Refunded')], default='held', max_length=20),
        ),
        migrations.CreateModel(
            name='TwoWayBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('missed_connection', 'Missed Connection'), ('recovered', 'Recovered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fare_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('connection_buffer_minutes', models.PositiveSmallIntegerField(default=30, help_text='Minimum buffer time between legs in minutes')),
                ('recovery_option_chosen', models.CharField(blank=True, choices=[('none', 'None'), ('re_route', 'Re-Route'), ('refund', 'Refund')], default='none', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('first_leg_boarded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('voucher_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('voucher_expires_at', models.DateTimeField(blank=True, null=True)),
                ('commuter', models.ForeignKey(limit_choices_to={'role': 'commuter'}, on_delete=django.db.models.deletion.CASCADE, related_name='two_way_bookings', to=settings.AUTH_USER_MODEL)),
                ('recovery_trip', models.ForeignKey(blank=True, help_text='Alternative trip if user chose re-route option', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recovery_bookings', to='routing.trip')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('transfer_station', models.ForeignKey(blank=True, help_text='Transfer station between legs (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two_way_bookings', to='routing.stop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='two_way_booking',
            field=models.ForeignKey(blank=True, help_text='Parent two-way booking if this is a leg of a round trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legs', to='booking.twowaybooking'),
        ),
    ]
