# Generated by Django 5.0.6 on 2026-07-10 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_is_two_way_booking_leg_order_and_more'),
        ('routing', '0005_transferstation_linkedroute'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fare_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('return_leg_modified', models.BooleanField(default=False)),
                ('modification_fee_waived', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('commuter', models.ForeignKey(limit_choices_to={'role': 'commuter'}, on_delete=django.db.models.deletion.CASCADE, related_name='booking_sessions', to=settings.AUTH_USER_MODEL)),
                ('return_leg_original_trip', models.ForeignKey(blank=True, help_text='Original return trip before modification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_return_sessions', to='routing.trip')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('reserved_future', 'Reserved Future'), ('locked_active', 'Locked Active'), ('released', 'Released'), ('expired', 'Expired')], default='reserved_future', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('commuter', models.ForeignKey(blank=True, limit_choices_to={'role': 'commuter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_reservations', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_reservations', to='routing.trip')),
            ],
            options={
                'ordering': ['reserved_at'],
            },
        ),
        migrations.CreateModel(
            name='TripLeg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leg_type', models.CharField(choices=[('outbound', 'Outbound'), ('return', 'Return')], help_text='Type of leg: outbound or return', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reserved_future', 'Reserved Future'), ('locked_active', 'Locked Active'), ('boarded', 'Boarded'), ('completed', 'Completed'), ('expired_missed', 'Expired/Missed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qr_code_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('seat_number', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('boarded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('alighting_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_leg_alightings', to='routing.stop')),
                ('boarding_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_leg_boardings', to='routing.stop')),
                ('booking_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_legs', to='booking.bookingsession')),
                ('commuter', models.ForeignKey(limit_choices_to={'role': 'commuter'}, on_delete=django.db.models.deletion.CASCADE, related_name='trip_legs', to=settings.AUTH_USER_MODEL)),
                ('seat_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_legs', to='booking.seatreservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_legs', to='routing.trip')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='trip_leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_reservations', to='booking.tripleg'),
        ),
        migrations.AlterUniqueTogether(
            name='seatreservation',
            unique_together={('trip', 'seat_number')},
        ),
    ]
