# Generated by Django 5.0.6 on 2026-07-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_bookingsession_seatreservation_tripleg_and_more'),
    ]

    operations = [
    ]
