# Generated by Django 5.0.6 on 2026-07-10 10:35

from django.db import migrations, models


def set_is_two_way_default(apps, schema_editor):
    """Set is_two_way to False for all existing bookings with NULL value."""
    Booking = apps.get_model('booking', 'Booking')
    Booking.objects.filter(is_two_way__isnull=True).update(is_two_way=False)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20260710_1328'),
    ]

    operations = [
        # First make the field nullable to allow updating existing NULL values
        migrations.AlterField(
            model_name='booking',
            name='is_two_way',
            field=models.BooleanField(default=False, help_text='Whether this is part of a two-way (round trip) booking', null=True),
        ),
        # Update all NULL values to False
        migrations.RunPython(set_is_two_way_default, migrations.RunPython.noop),
        # Now make the field NOT NULL again
        migrations.AlterField(
            model_name='booking',
            name='is_two_way',
            field=models.BooleanField(default=False, help_text='Whether this is part of a two-way (round trip) booking'),
        ),
    ]
