# Generated by Django 5.0.6 on 2026-07-11 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20260710_1335'),
        ('passes', '0004_remove_passusage_trip_leg'),
        ('payments', '0004_remove_payment_booking_session'),
        ('routing', '0005_transferstation_linkedroute'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripleg',
            name='booking_session',
        ),
        migrations.AlterUniqueTogether(
            name='seatreservation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seatreservation',
            name='commuter',
        ),
        migrations.RemoveField(
            model_name='seatreservation',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='seatreservation',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='seatreservation',
            name='trip_leg',
        ),
        migrations.RemoveField(
            model_name='tripleg',
            name='seat_reservation',
        ),
        migrations.RemoveField(
            model_name='tripleg',
            name='alighting_stop',
        ),
        migrations.RemoveField(
            model_name='tripleg',
            name='boarding_stop',
        ),
        migrations.RemoveField(
            model_name='tripleg',
            name='commuter',
        ),
        migrations.RemoveField(
            model_name='tripleg',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tripleg',
            name='trip',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('boarded', 'Boarded'), ('missed_delay', 'Missed Due to Delay'), ('re_routed', 'Re-Routed'), ('refunded', 'Refunded'), ('pending_transfer', 'Pending Transfer')], default='held', max_length=20),
        ),
        migrations.CreateModel(
            name='OpenReturnCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_amount', models.DecimalField(decimal_places=2, help_text='Amount credited for return trip fare', max_digits=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('valid_from', models.DateTimeField(help_text='Credit becomes valid at this time')),
                ('valid_until', models.DateTimeField(help_text='Credit expires at this time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_routes', models.ManyToManyField(blank=True, help_text='If specified, credit can only be used on these routes', related_name='open_return_credits', to='routing.route')),
                ('commuter', models.ForeignKey(limit_choices_to={'role': 'commuter'}, on_delete=django.db.models.deletion.CASCADE, related_name='open_return_credits', to=settings.AUTH_USER_MODEL)),
                ('outbound_booking', models.ForeignKey(help_text='The outbound trip booking that generated this credit', on_delete=django.db.models.deletion.CASCADE, related_name='issued_return_credits', to='booking.booking')),
                ('return_booking', models.ForeignKey(blank=True, help_text='The return trip booking that used this credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_return_credit', to='booking.booking')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BookingSession',
        ),
        migrations.DeleteModel(
            name='SeatReservation',
        ),
        migrations.DeleteModel(
            name='TripLeg',
        ),
    ]
