# Generated by Django 5.0.6 on 2026-07-11 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_remove_tripleg_booking_session_and_more'),
        ('routing', '0005_transferstation_linkedroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('single', 'Single'), ('return_outward', 'Return Outward'), ('return_inward', 'Return Inward'), ('link_leg_1', 'Link Leg 1'), ('link_leg_2', 'Link Leg 2')], default='single', help_text='Type of booking for multi-mode trip support', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='linked_booking',
            field=models.ForeignKey(blank=True, help_text='Linked booking for multi-mode trips', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_bookings', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pending_transfer_stop',
            field=models.ForeignKey(blank=True, help_text='Stop where passenger is pending transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_transfers', to='routing.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transfer_trigger_km',
            field=models.FloatField(default=2.0, help_text='Distance in km to trigger transfer notification'),
        ),
    ]
