# Generated by Django 5.0.6 on 2026-07-11 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_booking_booking_type_booking_linked_booking_and_more'),
        ('routing', '0005_transferstation_linkedroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pending_transfer_stop',
            field=models.ForeignKey(blank=True, help_text='Transfer station where passenger is pending transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_transfers', to='routing.transferstation'),
        ),
    ]
