# Generated by Django 5.0.6 on 2026-07-11 08:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_booking_pending_transfer_stop'),
        ('routing', '0005_transferstation_linkedroute'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('boarded', 'Boarded'), ('missed_delay', 'Missed Due to Delay'), ('re_routed', 'Re-Routed'), ('refunded', 'Refunded'), ('pending_transfer', 'Pending Transfer'), ('pending_manual_reroute', 'Pending Manual Reroute')], default='held', max_length=25),
        ),
        migrations.CreateModel(
            name='BookingReassignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('bus_cancelled', 'Bus Cancelled'), ('severe_delay', 'Severe Delay'), ('no_show', 'No Show'), ('maintenance', 'Maintenance Issue'), ('other', 'Other')], default='bus_cancelled', help_text='Reason for the reassignment', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending_manual', 'Pending Manual Reroute'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='success', help_text='Status of the reassignment attempt', max_length=20)),
                ('original_departure_time', models.DateTimeField(blank=True, help_text='Original scheduled departure time', null=True)),
                ('new_departure_time', models.DateTimeField(blank=True, help_text='New scheduled departure time', null=True)),
                ('original_vehicle_plate', models.CharField(blank=True, help_text='Original vehicle plate number', max_length=20, null=True)),
                ('new_vehicle_plate', models.CharField(blank=True, help_text='New vehicle plate number', max_length=20, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin if manual intervention was required')),
                ('notification_sent', models.BooleanField(default=False, help_text='Whether commuter was notified of the reassignment')),
                ('notification_sent_at', models.DateTimeField(blank=True, help_text='When the notification was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text='Admin who handled manual rerouting if required', limit_choices_to={'role__in': ['fleet_owner', 'super_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reassignments', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(help_text='The booking that was reassigned', on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='booking.booking')),
                ('new_trip', models.ForeignKey(blank=True, help_text='The new trip the booking was reassigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_reassignments', to='routing.trip')),
                ('original_trip', models.ForeignKey(blank=True, help_text='The original trip that was cancelled/delayed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_reassignments', to='routing.trip')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='booking_boo_status_8184fe_idx'), models.Index(fields=['reason'], name='booking_boo_reason_489cc8_idx'), models.Index(fields=['created_at'], name='booking_boo_created_441d20_idx')],
            },
        ),
    ]
