# Generated by Django 5.0.6 on 2026-07-07 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0004_vehicle_fleet_code'),
        ('routing', '0003_seat'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('loading_bay_capacity', models.PositiveIntegerField(default=2, help_text='Max buses allowed in the loading bay simultaneously.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='routing.route')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('holding', 'In holding zone'), ('called_up', 'Called to loading bay'), ('loading', 'Loading passengers'), ('departed', 'Departed'), ('skipped', 'Skipped by stage manager')], default='holding', max_length=20)),
                ('confirmed', models.BooleanField(default=False, help_text='Stage manager has physically verified this bus has arrived.')),
                ('time_cap_minutes', models.PositiveIntegerField(default=15, help_text='How long this bus may stay in the loading bay before being flagged.')),
                ('arrived_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('called_up_at', models.DateTimeField(blank=True, null=True)),
                ('loading_started_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('time_cap_exceeded', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='routing.route')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queue_entries', to='fleet.vehicle')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='stage_queue.stage')),
            ],
            options={
                'ordering': ['arrived_at'],
            },
        ),
    ]
