# Generated by Django 5.0.6 on 2026-07-08 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_seat'),
        ('stage_queue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queueentry',
            options={'ordering': ['position', 'arrived_at']},
        ),
        migrations.AddField(
            model_name='queueentry',
            name='conductor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'conductor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor_queue_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Manual position in queue for stage manager reordering.'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entry', to='routing.trip'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('holding', 'In holding zone'), ('called_up', 'Called to loading bay'), ('loading', 'Loading passengers'), ('departed', 'Departed'), ('skipped', 'Skipped by stage manager'), ('full', 'Vehicle full, ready to depart')], default='holding', max_length=20),
        ),
    ]
