# Generated by Django 5.0.6 on 2026-06-19 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0003_vehicle_inspection_expiry_vehicle_insurance_expiry'),
        ('routing', '0003_seat'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_phone', models.CharField(max_length=20)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('registered', 'Registered at origin'), ('loaded', 'Loaded onto vehicle'), ('in_transit', 'In transit'), ('arrived', 'Arrived at destination terminal'), ('collected', 'Collected by recipient')], default='registered', max_length=20)),
                ('qr_token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels_destination', to='routing.stop')),
                ('origin_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels_origin', to='routing.stop')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
                ('trip', models.ForeignKey(blank=True, help_text='The trip this parcel is travelling on.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='routing.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParcelScanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('loaded', 'Loaded onto vehicle'), ('offloaded', 'Offloaded at destination'), ('collected', 'Collected by recipient')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='parcels.parcel')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcel_scans', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcel_scans', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['scanned_at'],
            },
        ),
    ]
